// codebase-memory-mcp:start
// Generated by codebase-memory-mcp for pi.
// Regenerated on install/update from the MCP tool registry, so it cannot
// drift from the tools the server actually serves. Edits inside this block
// are overwritten; edit outside it, or remove the markers to take ownership.
// Target: @earendil-works/pi-coding-agent >= 0.74.0 (verified 0.84.2)
// ToolDefinition.execute(toolCallId, params, signal, onUpdate, ctx)
import { spawn } from 'node:child_process';

const BIN = '/Users/sezam/.local/bin/codebase-memory-mcp';

async function call(tool, args, signal) {
  return new Promise((resolve) => {
    const child = spawn(BIN, ['cli', '--json', tool], {
      stdio: ['pipe', 'pipe', 'pipe'],
      env: { ...process.env, CBM_LOG_LEVEL: 'error' },
    });
    let out = '';
    let stdinError;
    const onAbort = () => { if (!child.killed) child.kill(); };
    signal?.addEventListener('abort', onAbort, { once: true });
    child.stdout.on('data', (d) => (out += d.toString()));
    child.stdin.on('error', (e) => { stdinError = e; });
    child.on('error', (e) => {
      signal?.removeEventListener('abort', onAbort);
      resolve({ error: String(e && e.message ? e.message : e) });
    });
    child.on('close', () => {
      signal?.removeEventListener('abort', onAbort);
      const lines = out.split('\n').map((l) => l.trim()).filter(Boolean);
      for (let i = lines.length - 1; i >= 0; i--) {
        try { return resolve(JSON.parse(lines[i])); } catch { /* keep scanning */ }
      }
      if (stdinError) {
        return resolve({ error: String(stdinError.message || stdinError) });
      }
      resolve({ error: 'no JSON response from codebase-memory-mcp' });
    });
    child.stdin.end(JSON.stringify(args ?? {}));
  });
}

export default function (pi) {
  pi.registerTool({
    name: 'index_repository',
    label: 'index_repository',
    description: 'Index a repository. full/moderate add semantics; fast omits them; cross-repo-intelligence links services. Reports coverage gaps.',
    parameters: {"type":"object","properties":{"repo_path":{"type":"string","description":"Repository path"},"mode":{"type":"string","enum":["full","moderate","fast","cross-repo-intelligence"],"default":"full","description":"full: all+semantic; moderate: filtered+semantic; fast: filtered only; cross-repo-intelligence: link services."},"target_projects":{"type":"array","items":{"type":"string"},"description":"Cross-repo targets; [\"*\"] means all."},"name":{"type":"string","description":"Name override; Non-ASCII bytes are encoded; unsafe characters normalized."},"persistence":{"type":"boolean","default":false,"description":"Write .codebase-memory/graph.db.zst."}},"required":["repo_path"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('index_repository', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'search_graph',
    label: 'search_graph',
    description: 'Find symbols via BM25 query, regex name/qn filters, or semantic_query. Rows keep qn/file/lines and in/out over CALLS/USAGE/CALL_REFERENCE/INHERITS/IMPLEMENTS.',
    parameters: {"type":"object","properties":{"project":{"type":"string"},"query":{"type":"string"},"label":{"type":"string"},"name_pattern":{"type":"string"},"qn_pattern":{"type":"string"},"file_pattern":{"type":"string"},"relationship":{"type":"string"},"min_degree":{"type":"integer"},"max_degree":{"type":"integer"},"exclude_entry_points":{"type":"boolean"},"include_connected":{"type":"boolean"},"semantic_query":{"type":"array","items":{"type":"string"},"description":"Not with query."},"semantic_limit":{"type":"integer","default":50,"minimum":0,"maximum":500},"semantic_offset":{"type":"integer","default":0,"minimum":0,"maximum":99998},"limit":{"type":"integer","default":50,"minimum":1,"maximum":500},"offset":{"type":"integer","default":0,"minimum":0},"max_output_tokens":{"type":"integer","default":3200,"minimum":128,"maximum":1000000},"format":{"type":"string","enum":["tree","json"],"default":"tree"},"fields":{"type":"array","items":{"type":"string"}},"detail":{"type":"string","enum":["ids","default"],"default":"default"}},"required":["project"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('search_graph', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'query_graph',
    label: 'query_graph',
    description: 'Read-only Cypher for multi-hop, aggregation, complexity, or cross-service analysis. Default: 200 visible rows with exact/lower-bound totals and truncation; continue safely with next_cursor. graph=missed is a file tree of flagged coverage gaps; absence is not proof of completeness. Use get_graph_schema(diagnostics=full) for properties.',
    parameters: {"type":"object","properties":{"query":{"type":"string","description":"Cypher query"},"project":{"type":"string"},"graph":{"type":"string","enum":["code","missed"],"default":"code","description":"code graph (default) or missed coverage-gap file tree."},"max_rows":{"type":"integer","description":"Visible rows (default 200; max 99998); 0 uses the legacy maximum. Evaluation is unchanged.","minimum":0,"default":200},"offset":{"type":"integer","minimum":0,"default":0,"description":"Live compatibility paging; cannot be combined with cursor."},"cursor":{"type":"string","description":"Snapshot continuation; keep query/project/graph. Format, budget, and max_rows may change."},"max_output_tokens":{"type":"integer","minimum":128,"maximum":1000000,"description":"Sizing hint; hard ceiling is 4 UTF-8 bytes/token. Rows stay whole."},"format":{"type":"string","enum":["tree","json"],"default":"tree","description":"tree may use local @N+suffix prefix refs; json uses direct strings."}},"required":["query","project"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('query_graph', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'trace_path',
    label: 'trace_path',
    description: 'Trace callers/callees, data flow, or cross-service paths. Defaults exclude tests and resolver evidence. Rows keep qn/hop with explicit totals, relations, and continuations.',
    parameters: {"type":"object","properties":{"function_name":{"type":"string"},"project":{"type":"string"},"direction":{"type":"string","enum":["inbound","outbound","both"],"default":"both"},"depth":{"type":"integer","default":3,"minimum":1,"maximum":15},"limit":{"type":"integer","default":100,"minimum":1,"maximum":5000,"description":"Rows/page; gte flags the 5000-node engine ceiling."},"max_output_tokens":{"type":"integer","default":3200,"minimum":128,"maximum":1000000,"description":"Sizing hint; hard ceiling is 4 UTF-8 bytes/token. Evidence/args yield before nearest graph rows."},"cursor":{"type":"string","description":"Pass next/next_cursor with traversal args unchanged; budget may increase."},"mode":{"type":"string","enum":["calls","data_flow","cross_service"],"default":"calls","description":"calls, argument-aware data_flow, or service edges."},"parameter_name":{"type":"string","description":"data_flow parameter filter."},"edge_types":{"type":"array","items":{"type":"string"}},"risk_labels":{"type":"boolean","default":false,"description":"Add hop-risk labels."},"include_tests":{"type":"boolean","default":false},"format":{"type":"string","enum":["tree","json"],"default":"tree","description":"tree chooses smaller complete direct/grouped output; json uses stable grouped tables."},"include_evidence":{"type":"boolean","default":false,"description":"Add resolver class and confidence."}},"required":["function_name","project"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('trace_path', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'get_code_snippet',
    label: 'get_code_snippet',
    description: 'Read a search_graph symbol. auto bounds source and outlines large containers; full restores up to 500 lines. Source/outline pages continue; coverage_note marks gaps.',
    parameters: {"type":"object","properties":{"qualified_name":{"type":"string","description":"search_graph qn, or short name."},"project":{"type":"string"},"include_neighbors":{"type":"boolean","default":false},"source_mode":{"type":"string","enum":["auto","full","outline"],"default":"auto","description":"auto outlines 200+ line containers; full returns source; outline lists members."},"member_limit":{"type":"integer","default":50,"minimum":1,"maximum":500},"member_offset":{"type":"integer","default":0,"minimum":0},"start_line":{"type":"integer","minimum":1},"max_lines":{"type":"integer","minimum":1,"maximum":500},"max_output_tokens":{"type":"integer","minimum":128,"maximum":1000000,"description":"auto/outline sizing hint (default 2500), hard ceiling 4 UTF-8 bytes/token. Lines stay whole; explicit full is uncapped unless set."},"format":{"type":"string","enum":["tree","json"],"default":"tree"}},"required":["qualified_name","project"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('get_code_snippet', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'get_file_outline',
    label: 'get_file_outline',
    description: 'Declaration outline of one exact repository-relative file: optional exact label filter, source order, exact total/offset/limit paging; file/folder/container nodes excluded.',
    parameters: {"type":"object","properties":{"project":{"type":"string"},"file_path":{"type":"string","description":"Exact repository-relative file path"},"labels":{"type":"array","items":{"type":"string"},"maxItems":16,"description":"Optional exact node-label filter"},"limit":{"type":"integer","minimum":1,"maximum":200,"default":100},"offset":{"type":"integer","minimum":0,"default":0},"format":{"type":"string","enum":["tree","json"],"default":"tree"}},"additionalProperties":false,"required":["project","file_path"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('get_file_outline', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'get_graph_schema',
    label: 'get_graph_schema',
    description: 'Get node-label and edge-type counts. diagnostics=full also lists queryable properties.',
    parameters: {"type":"object","properties":{"project":{"type":"string"},"format":{"type":"string","enum":["tree","json"],"default":"tree"},"diagnostics":{"type":"string","enum":["none","full"],"default":"none"},"limit":{"type":"integer","default":50,"minimum":1,"maximum":500},"offset":{"type":"integer","default":0,"minimum":0}},"required":["project"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('get_graph_schema', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'compare_graphs',
    label: 'compare_graphs',
    description: 'Compare two indexed snapshots: deterministic target-only additions and base-only removals of stable node/edge identities; each set capped by limit and a 512 KiB budget with exact totals and truncation reasons.',
    parameters: {"type":"object","properties":{"base_project":{"type":"string","minLength":1},"target_project":{"type":"string","minLength":1},"limit":{"type":"integer","minimum":1,"maximum":1000,"default":200},"scan_limit":{"type":"integer","minimum":1,"maximum":10000000,"default":2000000}},"required":["base_project","target_project"],"additionalProperties":false},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('compare_graphs', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'get_architecture',
    label: 'get_architecture',
    description: 'Compact counts, languages, packages, entry points. Request structure, dependencies, routes, hotspots, boundaries, layers, clusters, cycles, or file_tree; path scopes a directory.',
    parameters: {"type":"object","properties":{"project":{"type":"string"},"path":{"type":"string","description":"Directory prefix (for example apps/hoa)."},"aspects":{"type":"array","items":{"type":"string","enum":["all","overview","structure","dependencies","routes","languages","packages","entry_points","hotspots","boundaries","layers","file_tree","clusters","cycles"]},"description":"all=everything; overview=compact except file_tree; omitted=languages/packages/entry_points; cycles is opt-in."},"format":{"type":"string","enum":["tree","json"],"default":"tree"}},"required":["project"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('get_architecture', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'search_code',
    label: 'search_code',
    description: 'Graph-ranked text search: compact symbols, full bounded source, or file paths.',
    parameters: {"type":"object","properties":{"pattern":{"type":"string"},"project":{"type":"string"},"file_pattern":{"type":"string"},"path_filter":{"type":"string"},"mode":{"type":"string","enum":["compact","full","files"],"default":"compact"},"context":{"type":"integer"},"regex":{"type":"boolean","default":false},"debug":{"type":"boolean","default":false,"description":"Add scope_ms/scan_ms/enrich_ms phase timings."},"limit":{"type":"integer","default":10,"minimum":1,"maximum":500},"result_limit":{"type":"integer","default":10,"minimum":1,"maximum":500},"result_offset":{"type":"integer","default":0,"minimum":0},"raw_limit":{"type":"integer","default":5,"minimum":0,"maximum":100},"raw_offset":{"type":"integer","default":0,"minimum":0},"raw_content_offset":{"type":"integer","minimum":0,"description":"Raw-line byte offset; omit for match-centered preview."},"directory_limit":{"type":"integer","default":20,"minimum":0,"maximum":64},"directory_offset":{"type":"integer","default":0,"minimum":0},"match_limit":{"type":"integer","default":8,"minimum":1,"maximum":500},"source_max_lines":{"type":"integer","default":20,"minimum":1,"maximum":200},"max_output_tokens":{"type":"integer","minimum":128,"maximum":1000000},"format":{"type":"string","enum":["tree","json"],"default":"tree"}},"required":["pattern","project"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('search_code', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'list_projects',
    label: 'list_projects',
    description: 'List projects with stable paging. Identity is lean; stats adds graph sizes.',
    parameters: {"type":"object","properties":{"format":{"type":"string","enum":["tree","json"],"default":"tree"},"detail":{"type":"string","enum":["identity","stats"],"default":"identity","description":"stats adds node/edge/database-size counts."},"include_details":{"type":"boolean","default":false,"description":"Alias for detail=stats: include branch, node/edge counts and database size. Slower."},"limit":{"type":"integer","default":50,"minimum":1,"maximum":500},"offset":{"type":"integer","default":0,"minimum":0},"metadata_only":{"type":"boolean","default":false,"description":"Compatibility: omit counts, size, and branch."}}},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('list_projects', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'delete_project',
    label: 'delete_project',
    description: 'Delete a project from the index',
    parameters: {"type":"object","properties":{"project":{"type":"string"}},"required":["project"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('delete_project', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'index_status',
    label: 'index_status',
    description: 'Project readiness, counts, root, and coverage gaps. diagnostics adds coverage rows; verbose adds Git paths. Best-effort only; verify cited paths with check_index_coverage.',
    parameters: {"type":"object","properties":{"project":{"type":"string"},"verbose":{"type":"boolean","default":false,"description":"Add worktree/shadow Git paths for index-location debugging."},"diagnostics":{"type":"string","enum":["none","summary","full"],"default":"none","description":"Coverage rows: counts, five samples, or up to 500."},"format":{"type":"string","enum":["tree","json"],"default":"tree"}},"required":["project"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('index_status', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'check_index_coverage',
    label: 'check_index_coverage',
    description: 'Best-effort exact-path/scope coverage and freshness, paged separately. full diagnostics adds raw detail. Clean is not proof of completeness.',
    parameters: {"type":"object","properties":{"project":{"type":"string"},"paths":{"type":"array","items":{"type":"string"},"maxItems":128},"path_limit":{"type":"integer","default":20,"minimum":1,"maximum":128},"path_offset":{"type":"integer","default":0,"minimum":0},"scopes":{"type":"array","items":{"type":"string"},"maxItems":32},"scope_limit":{"type":"integer","default":20,"minimum":1,"maximum":1000},"scope_offset":{"type":"integer","default":0,"minimum":0},"diagnostics":{"type":"string","enum":["none","full"],"default":"none"},"format":{"type":"string","enum":["tree","json"],"default":"tree"}},"required":["project"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('check_index_coverage', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'detect_changes',
    label: 'detect_changes',
    description: 'Map a Git diff to files and impact. Page with snapshot cursors.',
    parameters: {"type":"object","properties":{"project":{"type":"string"},"scope":{"type":"string","enum":["files","impact"],"default":"impact"},"direction":{"type":"string","enum":["inbound","outbound","both"],"default":"inbound","description":"inbound=callers; outbound=dependencies; both=union."},"depth":{"type":"integer","default":2},"limit":{"type":"integer","default":200,"maximum":5000},"impact_offset":{"type":"integer","default":0,"minimum":0},"impact_cursor":{"type":"string"},"changed_limit":{"type":"integer","default":20,"minimum":0,"maximum":5000},"changed_offset":{"type":"integer","default":0,"minimum":0},"changed_cursor":{"type":"string"},"module_limit":{"type":"integer","default":20,"minimum":0,"maximum":256},"module_offset":{"type":"integer","default":0,"minimum":0},"module_cursor":{"type":"string"},"max_output_tokens":{"type":"integer","default":3200,"minimum":128,"maximum":1000000,"description":"Sizing hint; hard ceiling is 4 UTF-8 bytes/token."},"base_branch":{"type":"string","default":"main"},"since":{"type":"string"},"format":{"type":"string","enum":["tree","json"],"default":"tree"}},"required":["project"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('detect_changes', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'manage_adr',
    label: 'manage_adr',
    description: 'Outline an ADR by default; get reads it; update replaces it',
    parameters: {"type":"object","properties":{"project":{"type":"string"},"mode":{"type":"string","enum":["outline","get","update","set_sections","sections"],"default":"outline","description":"outline pages headings; get reads; update replaces the whole document; set_sections rewrites only the named sections and leaves every other byte untouched (an identical repeated write is byte-identical, so retrying is safe); sections is legacy."},"content":{"type":"string","description":"Whole document for update"},"section_updates":{"type":"object","description":"set_sections: section name -> new body. Any heading name works; names match exactly, including case.","additionalProperties":{"type":"string"}},"section_limit":{"type":"integer","default":50,"minimum":1,"maximum":500},"section_offset":{"type":"integer","default":0,"minimum":0},"format":{"type":"string","enum":["tree","json"],"default":"tree"}},"additionalProperties":false,"required":["project"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('manage_adr', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
  pi.registerTool({
    name: 'ingest_traces',
    label: 'ingest_traces',
    description: 'Validate and count traces; graph edge creation is not implemented',
    parameters: {"type":"object","properties":{"traces":{"type":"array","items":{"type":"object","properties":{"caller":{"type":"string"},"callee":{"type":"string"},"count":{"type":"integer"}},"additionalProperties":false}},"project":{"type":"string"}},"required":["traces","project"]},
    execute: async (toolCallId, params, signal, _onUpdate, ctx) => {
      const result = await call('ingest_traces', params, signal ?? ctx?.signal);
      if (result && typeof result === 'object' && result.error) {
        throw new Error(String(result.error));
      }
      const content = result && Array.isArray(result.content)
        ? result.content
        : [{ type: 'text', text: JSON.stringify(result ?? null, null, 2) }];
      return { content, details: result ?? {} };
    },
  });
}
// codebase-memory-mcp:end
